### ISSUE TITLE
Comment Stripping TEAL source issue

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/algokit-utils-py#25]
The following program:

```py
def program():
    return pt.Seq(pt.Pop(pt.Bytes("//")), pt.Int(1))
```

Will generate
```
// GENERATED TEAL    //    PYTEAL PATH    LINE    PYTEAL
#pragma version 8    //    commentary.py  30      Compilation(approval_program, mode=Mode.Application, version=8).compile(with_sourcemap=True, annotate_teal=True, annotate_teal_headers=True)
byte "//"            //                   21      pt.Bytes('//')
pop                  //                           pt.Pop(pt.Bytes('//'))
int 1                //                           pt.Int(1)
return               //                   30      Compilation(approval_program, mode=Mode.Application, version=8).compile(with_sourcemap=True, annotate_teal=True, annotate_teal_headers=True)
```

Which will break with our current approach to strip comments
https://github.com/algorandfoundation/algokit-utils-py/blob/main/src/algokit_utils/deploy.py#L310-L312

**Comment by tzaffi** [comment]
The approach of stripping out comments is probably workable, but handling all the edge cases seems -at first blush- tedious and error prone. Another approach follows (repurposed from a discussion on [beaker #246](https://github.com/algorand-devrel/beaker/pull/226)):

the annotated teal pc=>line map always the same as the non-annotated one as long as headers are _excluded_ from the annotation (`annotate_teal_headers=False`).

This is ensured both for the router and for the compiler.

For the router we can follow this trail:

* `compile` calls [get_results()](https://github.com/algorand/pyteal/blob/e0eb54cdbe70a630ba5b1f68d2c64078946eb1ff/pyteal/ast/router.py#L1301)
* which calls [get_sourcemap(self.approval_teal)](https://github.com/algorand/pyteal/blob/e0eb54cdbe70a630ba5b1f68d2c64078946eb1ff/pyteal/ast/router.py#L864)
* which calls [_validate_annotated()](https://github.com/algorand/pyteal/blob/c361a636cd623ea3fe0589af1577ededb1cf8a05/pyteal/compiler/sourcemap.py#L754) 
* which [asserts](https://github.com/algorand/pyteal/blob/c361a636cd623ea3fe0589af1577ededb1cf8a05/pyteal/compiler/sourcemap.py#L1330-L1333) that each line of the annotated teal starts with the corresponding line of `self.approval_teal`

Note that `self.approval_teal` is the [approval program returned](https://github.com/algorand/pyteal/blob/e0eb54cdbe70a630ba5b1f68d2c64078946eb1ff/pyteal/ast/router.py#L871) by `Router.compile()`.

**Comment by daniel-makerx** [comment]
I think @tzaffi suggestions will be the more robust method, however that would have to be done outside this library i.e. in beaker or other consumers of PyTeal as the client here only depends on the app spec. 

What I could do is provide a way to set an optional annotated source file and source map on the algokit utils client that is used during error handling, or alternatively we could go back to the original idea of having the annotated source included in the app spec. @barnjamin What do you think?

**Comment by barnjamin** [comment]
Even if we do something in beaker for this, I think the above program would cause issues since the comment stripper fn does not make a distinction between annotated/non-annotated programs.
