### ISSUE TITLE
AVM Debugger compliant sourcemap and simulation trace file.

### ISSUE THREAD

**Issue by BMscis** [algorandfoundation/algokit-utils-py#64]
```py
# Uncomment the following lines to enable auto generation of AVM Debugger compliant sourcemap and simulation trace file.
# Learn more about using AlgoKit AVM Debugger to debug your TEAL source codes and inspect various kinds of
# Algorand transactions in atomic groups -> https://github.com/algorandfoundation/algokit-avm-vscode-debugger
from algokit_utils.config import config
config.configure(debug=True, trace_all=True)
```

Can't seem to be able to generate sourcemaps and trace file from an algokit init project.

[tool.poetry.dependencies]
python = "^3.10"
beaker-pyteal = "^1.1.1"
algokit-utils = "^2.2.0"
python-dotenv = "^1.0.0"

**Comment by aorumbayev** [comment]
Hey there @BMscis can you copy and paste the output of `algokit doctor` command and steps to replicate the bug?

After uncommenting those lines have you redeployed contracts or run the unit test (that also rely on an app client class). The artifacts are auto generated but only when you perform deploy your contracts via app client. The sourcemaps are dumped into `.algokit` folder on the same level as your `algokit.toml` file location and simulation traces at `debug_traces`
You can also use the utils that are used to autogenerate the artifacts implicitly during deployment (or any app call via app client) directly -> https://github.com/algorandfoundation/algokit-utils-py/blob/main/docs/source/capabilities/debugging.md#debugging-utilities in that case you are free to control how and when those artifacts get generated.

**Comment by BMscis** [comment]
algokit doctor:
```cli
timestamp: 2024-01-03T00:10:15+00:00
AlgoKit: 1.9.0 (latest: 1.9.1)
AlgoKit Python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] (location: C:\Users\alienware\.local\pipx\venvs\algokit)
OS: Windows-10-10.0.22000-SP0
docker: 20.10.24
docker compose: 2.17.2
git: 2.40.0.windows.1
python: 3.11.3 (location: C:\Users\alienware\Documents\git\soti\project\soti_marketplace\backend\.venv/Scripts\python.EXE)
python3: Command exited with code: 9009
  Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
pipx: 1.2.0
poetry: 1.4.2
node: 18.16.0
npm: 9.5.1
chocolatey: Command not found!

If you are experiencing a problem with AlgoKit, feel free to submit an issue via:
https://github.com/algorandfoundation/algokit-cli/issues/new
Please include this output, if you want to populate this message in your clipboard, run `algokit doctor -c`
```

I can see the sources folder now. It wasn't showing anything last week. Thanks.

**Comment by BMscis** [comment]
I can see the sources folder now. It wasn't showing anything last week. Thanks.
